
services:
  # Laravel Service
  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"  # or "80:8000" if you want to access via port 80
    networks:
      - app-network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_DATABASE=inswal
      - DB_USERNAME=oniologdb
      - DB_PASSWORD=onion1680
    # Ensure the backend waits for the db to start

  # React Service
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend  # Ensure frontend waits for backend to start

  # MySQL Service
   
   

networks:
  app-network:
    
    driver: bridge

volumes:
  dbdata:
